### ISSUE TITLE
Usage of library under linux / Ubuntu

### ISSUE THREAD

**Issue by K-Zanaty** [ingeniamc/ingeniamotion#117]
Dear contributors,

I was wondering if I could use the ingeniamotion package to build a linux application running as a service. I understand that the usage under Windows requires WinPcap. However, a connection and read/write operations to ingenia drives should be also possible through linux as well? Do I need to consider any special requirements?

@GullinBustin @WoodElv 

Thanks a lot and best!
Karim

**Comment by GullinBustin** [comment]
Nowadays ingeniamotion in Linux can only use ethernet, CANopen, and EoE with an external master
